version: '3.8'

services:
  react-app:
    build: ./front
    container_name: react-app
    ports:
      - "3001:3001"
    depends_on:
      - api

  api:
    build: ./urna2-api
    container_name: spring-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=pablo
      - SPRING_DATASOURCE_PASSWORD=pablo
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=pablo
      - POSTGRES_PASSWORD=pablo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: