version: '3.8'

services:
  backend:
    build: ./urna2-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=pablo
      - SPRING_DATASOURCE_PASSWORD=pablo
    depends_on:
      - db
    networks:
      - app-network
  frontend:
    build: ./front
    ports:
      - "5173:5173"
    networks:
      - app-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pablo
      POSTGRES_PASSWORD: pablo
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
